services:
  minio:
    image: wlcamargo/minio
    container_name: minio
    networks:
      - bigdata
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

  db:
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5435:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgres_local
    restart: always

networks:
  bigdata:
    driver: bridge
volumes:
  minio-data:
  db_data:
    driver: local
