services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer_local
    init: true
    restart: always
    ports:
      - "9003:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data