services:
  db:
    build: ./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgres_local
    restart: always

volumes:
  db_data:
    driver: local